# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d4aebf89d1de444e127d69afef8b2f50644ca0d3da5868b3ebea900d26d551ebb54c9462100bed355dc1419995b20fd7ac2431d9ddad2030e6333c0c52780d

test:
  secret_key_base: 90356ed1ae327b506f3f6f36cb044660b86548733c65ea9c9bd217fbf43274e76c53d91bf09a2bd5a7e2b71841cd405f50a72d931d682af4dedcbe1f14ecc1a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
